# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-correct', 'created'], 'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-modified'], 'verbose_name': 'Tópico', 'verbose_name_plural': 'Tópicos'},
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='modified_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='modified_at',
            new_name='modified',
        ),
    ]
