# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordreset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nova Senha', 'verbose_name_plural': 'Novas Senhas'},
        ),
    ]
